INSERT INTO GestaoEscola.Funcionario (PNMec,salario) VALUES (273, 750)
INSERT INTO GestaoEscola.Funcionario (PNMec,salario) VALUES (209, 990)
INSERT INTO GestaoEscola.Funcionario (PNMec,salario) VALUES (531, 630)
INSERT INTO GestaoEscola.Funcionario (PNMec,salario) VALUES (329, 750)
INSERT INTO GestaoEscola.Funcionario (PNMec,salario) VALUES (150, 990)
INSERT INTO GestaoEscola.Funcionario (PNMec,salario) VALUES (244, 630)
INSERT INTO GestaoEscola.Funcionario (PNMec,salario) VALUES (684, 750)
INSERT INTO GestaoEscola.Funcionario (PNMec,salario) VALUES (847, 990)
INSERT INTO GestaoEscola.Funcionario (PNMec,salario) VALUES (791, 630)
INSERT INTO GestaoEscola.Funcionario (PNMec,salario) VALUES (814, 750)
INSERT INTO GestaoEscola.Funcionario (PNMec,salario) VALUES (156, 990)
INSERT INTO GestaoEscola.Funcionario (PNMec,salario) VALUES (815, 630)
INSERT INTO GestaoEscola.Funcionario (PNMec,salario) VALUES (475, 750)
INSERT INTO GestaoEscola.Funcionario (PNMec,salario) VALUES (347, 990)
INSERT INTO GestaoEscola.Funcionario (PNMec,salario) VALUES (603, 630)
INSERT INTO GestaoEscola.Funcionario (PNMec,salario) VALUES (155, 750)
INSERT INTO GestaoEscola.Funcionario (PNMec,salario) VALUES (782, 990)
INSERT INTO GestaoEscola.Funcionario (PNMec,salario) VALUES (471, 630)
INSERT INTO GestaoEscola.Funcionario (PNMec,salario) VALUES (940, 750)
INSERT INTO GestaoEscola.Funcionario (PNMec,salario) VALUES (856, 990)

-- 20 lines processed, resulting in 0 tuples!
